apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: nginx
  namespace: argocd

spec:

  generators:

  - list:
      elements:

      - environment: prod
        namespace: nginx-prod
        cluster: https://kubernetes.default.svc
        values: prod.yaml

  template:

    metadata:
      name: nginx-{{environment}}

    spec:

      project: default


      source:

        repoURL: git@github.com:rknoplock/gitops-knoplock.git

        targetRevision: main


        path: charts/nginx


        helm:

          valueFiles:

          - ../../apps/nginx/{{values}}



      destination:

        server: "{{cluster}}"

        namespace: "{{namespace}}"


      syncPolicy:

        automated:

          prune: true

          selfHeal: true


        syncOptions:

        - CreateNamespace=true