apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rknoplock/gitops-knoplock.git
    targetRevision: main
    path: charts/nginx
    helm:
      parameters:
        - name: replicaCount
          value: "2"
        - name: image.tag
          value: "1.27"
      values: |-
        image:
          repository: nginx
        service:
          type: ClusterIP
          port: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true