apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rknoplock/gitops-knoplock.git
    targetRevision: main
    path: charts/podinfo
    helm:
      parameters:
        - name: replicaCount
          value: "1"
        - name: image.tag
          value: "6.7.0"
      values: |-
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true